# Generated by Django 2.2.5 on 2020-11-11 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0002_auto_20201111_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Username',
            new_name='username',
        ),
    ]
