# Generated by Django 2.2.5 on 2020-11-11 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0003_auto_20201111_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
    ]
