# Generated by Django 3.1.3 on 2020-12-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0004_remove_employee_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customertargetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_address', models.CharField(max_length=255)),
                ('customer_type', models.CharField(max_length=50)),
                ('keyword', models.CharField(max_length=100)),
                ('radius', models.CharField(max_length=20)),
                ('place_id', models.CharField(max_length=50)),
                ('latitude_origin', models.FloatField()),
                ('longitude_origin', models.FloatField()),
                ('latitude_destination', models.FloatField()),
                ('longitude_destination', models.FloatField()),
                ('phone_number', models.CharField(max_length=20)),
                ('distancedrive', models.CharField(max_length=50)),
                ('distancewalks', models.CharField(max_length=50)),
            ],
        ),
    ]
